pr: none

trigger: none # Not a CI build

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: $(Agent.TempDirectory)/bld
  testDir: $(buildDir)/tst
  PyVer: 3.6

jobs:
- job: Linux
  displayName: "Linux build"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Bash@3
    displayName: "Install latest CMake"
    inputs:
      scriptPath: scripts/cmakeupdate.sh
    
  - task: UsePythonVersion@0
    displayName: 'Use Python $(PyVer)'
    inputs:
      versionSpec: '$(PyVer)' 
      addToPath: true
  - script: pip install gcovr
    
  - task: CMake@1
    displayName: "Run CMake"
    inputs:
      cmakeArgs: $(Build.SourcesDirectory)
      workingDirectory: $(buildDir)

  - script: make -j VERBOSE=1
    displayName: "Build all"
    workingDirectory: $(buildDir)

  - script: ./LinesideTest --log_level=all --log_format=JUNIT --log_sink=test-results-JUNIT.xml --report_sink=stdout
    displayName: "Run all tests"
    workingDirectory: $(testDir)

  - task: PublishTestResults@2
    displayName: "Publish test results"
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*JUNIT.xml'
      searchFolder: $(testDir)
      failTaskOnFailedTests: true
      testRunTitle: 'Lineside Test Run'