pr: none

trigger: none # Not a CI build

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: $(Agent.TempDirectory)/bld
  testDir: $(buildDir)/tst
  PyVer: 3.6

jobs:
- job: Linux
  displayName: "Linux build"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Bash@3
    displayName: "Install latest CMake"
    inputs:
      filePath: scripts/cmakeupdate.sh
    
  - task: UsePythonVersion@0
    displayName: 'Use Python $(PyVer)'
    inputs:
      versionSpec: '$(PyVer)' 
      addToPath: true
      
  - script: pip install gcovr
    displayName: 'Install gcovr'

  - script: mkdir $(buildDir)
    displayName: 'Create build directory'
    
  - script: /usr/bin/cmake -DCMAKE_BUILD_TYPE=Debug $(Build.SourcesDirectory)
    displayName: "Run CMake"
    workingDirectory: $(buildDir)

  - script: make -j VERBOSE=1
    displayName: "Build all"
    workingDirectory: $(buildDir)

  - script: ./LinesideTest --log_level=all --log_format=JUNIT --log_sink=test-results-JUNIT.xml --report_sink=stdout
    displayName: "Run all tests"
    workingDirectory: $(testDir)

  - task: PublishTestResults@2
    displayName: "Publish test results"
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*JUNIT.xml'
      searchFolder: $(testDir)
      failTaskOnFailedTests: true
      testRunTitle: 'Lineside Test Run'

  - script: gcovr --root $(Build.SourcesDirectory) . --xml cobetura.xml --html-details html/details.html --print-summary
    displayName: "Run gcovr"
    workingDirectory: $(buildDir)

  - script: ls
    displayName: "Show dir contents"
    workingDirectory: $(buildDir)

  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage results"
    workingDirectory: $(buildDir)
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: cobetura.xml
      pathToSources: $(Build.SourcesDirectory)
      reportDirectory: html