pr: none

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: $(Agent.TempDirectory)/bld
  testDir: $(buildDir)/tst

jobs:
- job: Linux
  displayName: "Linux Documentation build"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: sudo apt-get install doxygen graphviz
    displayName: "Install doc prereqs"

  - task: Bash@3
    displayName: "Install latest CMake"
    inputs:
      filePath: scripts/cmakeupdate.sh
    
  - script: mkdir $(buildDir)
    displayName: 'Create build directory'
    
  - script: /usr/bin/cmake $(Build.SourcesDirectory)
    displayName: "Run CMake"
    workingDirectory: $(buildDir)

  - script: make docs
    displayName: "Build docs"
    workingDirectory: $(buildDir)

  - task: PublishBuildArtifacts@1
    displayName: "Publish docs as artifacts"
    inputs:
      artifactName: Documentation
      pathToPublish: $(buildDir)/docs