pr: none

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: $(Agent.TempDirectory)/bld
  testDir: $(buildDir)/tst

jobs:
- job: Linux
  displayName: "Linux Documentation build"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: sudo apt-get install doxygen graphviz
    displayName: "Install doc prereqs"

  - template: cmake-steps-template.yml
    parameters:
      srcDir: $(Build.SourcesDirectory)
      bldDir: $(buildDir)
      makeTarget: 'docs'

  - task: PublishBuildArtifacts@1
    displayName: "Publish docs as artifacts"
    inputs:
      artifactName: Documentation
      pathToPublish: $(buildDir)/docs