pr:
- master

trigger: none # No CI builds

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: $(Agent.TempDirectory)/bld
  testDir: $(buildDir)/tst

jobs:
- job: Linux
  displayName: "Linux build"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - template: cmake-steps-template.yml
    parameters:
      srcDir: $(Build.SourcesDirectory)
      bldDir: $(buildDir) 

  - script: ./LinesideTest --log_level=all --log_format=JUNIT --log_sink=test-results-JUNIT.xml --report_sink=stdout
    displayName: "Run all tests"
    workingDirectory: $(testDir)

  - task: PublishTestResults@2
    displayName: "Publish test results"
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*JUNIT.xml'
      searchFolder: $(testDir)
      failTaskOnFailedTests: true
      testRunTitle: 'Lineside Test Run'