pr:
- master

trigger: none # No CI builds


schedules:
- cron: "0 5 * * 6" # Time is UTC
  displayName: Saturday Gated Build
  branches:
    include:
      - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: $(Agent.TempDirectory)/bld
  testDir: $(buildDir)

jobs:
- job: Linux
  displayName: "Linux build"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - template: cmake-steps-template.yml
    parameters:
      srcDir: $(Build.SourcesDirectory)
      bldDir: $(buildDir) 

  - template: testing-steps-template.yml
    parameters:
      testDir: $(testDir)