pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildDir: $(Agent.TempDirectory)/bld
  testDir: $(buildDir)/tst

jobs:
- job: Linux
  displayName: "Linux build"
  pool:
    vmInage: 'ubuntu-latest'

  steps:
  - task: CMake@1
    displayName: "Build with CMake"
    inputs:
      workingDirectory: $(Agent.TempDirectory)/bld

  - script: ./LinesideTest --log_level=all --log_format=JUNIT --log_sink=test-results-JUNIT.xml --result_code=no --report_sink=stdout
    displayName: "Run all tests"
    workingDirectory: $(testDir)

  - task: PublishTestResults@2
    displayName: "Publish test results"
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*JUNIT.xml'
      searchFolder: $(testDir)
      failTaskOnFailedTests: true
      testRunTitle: 'Lineside Test Run'